/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ArticleRouteImport } from './routes/article'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as GamsRouteImport } from './routes/gams'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCommentsRouteImport } from './routes/admin/comments'
import { Route as AdminFieldsRouteImport } from './routes/admin/fields'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTezcoinRouteImport } from './routes/admin/tezcoin'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CaseStudySlugRouteImport } from './routes/case-study/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard/referrals'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as DownloadSlugRouteImport } from './routes/download/$slug'
import { Route as OnlineCalculationToolsIndexRouteImport } from './routes/online-calculation-tools/index'
import { Route as OnlineCalculationToolsSlugRouteImport } from './routes/online-calculation-tools/$slug'
import { Route as PayCallbackRouteImport } from './routes/pay/callback'
import { Route as ProposalIndexRouteImport } from './routes/proposal/index'
import { Route as ProposalSlugRouteImport } from './routes/proposal/$slug'
import { Route as ThesisIndexRouteImport } from './routes/thesis/index'
import { Route as ThesisSlugRouteImport } from './routes/thesis/$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as AdminFieldsSlugRouteImport } from './routes/admin/fields.$slug'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin/tickets/index'
import { Route as AdminTicketsIdRouteImport } from './routes/admin/tickets/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsIdRouteImport } from './routes/dashboard/projects/$id'
import { Route as DashboardTicketsIndexRouteImport } from './routes/dashboard/tickets/index'
import { Route as DashboardTicketsIdRouteImport } from './routes/dashboard/tickets/$id'
import { Route as ThesisHumanitiesSlugRouteImport } from './routes/thesis/humanities/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const GamsRoute = GamsRouteImport.update({
  id: '/gams',
  path: '/gams',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFieldsRoute = AdminFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTezcoinRoute = AdminTezcoinRouteImport.update({
  id: '/tezcoin',
  path: '/tezcoin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudySlugRoute = CaseStudySlugRouteImport.update({
  id: '/case-study/$slug',
  path: '/case-study/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DownloadSlugRoute = DownloadSlugRouteImport.update({
  id: '/download/$slug',
  path: '/download/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineCalculationToolsIndexRoute =
  OnlineCalculationToolsIndexRouteImport.update({
    id: '/online-calculation-tools/',
    path: '/online-calculation-tools/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineCalculationToolsSlugRoute =
  OnlineCalculationToolsSlugRouteImport.update({
    id: '/online-calculation-tools/$slug',
    path: '/online-calculation-tools/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PayCallbackRoute = PayCallbackRouteImport.update({
  id: '/pay/callback',
  path: '/pay/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalIndexRoute = ProposalIndexRouteImport.update({
  id: '/proposal/',
  path: '/proposal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalSlugRoute = ProposalSlugRouteImport.update({
  id: '/proposal/$slug',
  path: '/proposal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesisIndexRoute = ThesisIndexRouteImport.update({
  id: '/thesis/',
  path: '/thesis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesisSlugRoute = ThesisSlugRouteImport.update({
  id: '/thesis/$slug',
  path: '/thesis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldsSlugRoute = AdminFieldsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminFieldsRoute,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTicketsIdRoute = AdminTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsIdRoute = DashboardTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ThesisHumanitiesSlugRoute = ThesisHumanitiesSlugRouteImport.update({
  id: '/thesis/humanities/$slug',
  path: '/thesis/humanities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/article': typeof ArticleRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/downloads': typeof DownloadsRoute
  '/gams': typeof GamsRoute
  '/inquiry': typeof InquiryRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/project': typeof ProjectRoute
  '/refund': typeof RefundRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/simulation': typeof SimulationRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/fields': typeof AdminFieldsRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tezcoin': typeof AdminTezcoinRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/download/$slug': typeof DownloadSlugRoute
  '/online-calculation-tools/$slug': typeof OnlineCalculationToolsSlugRoute
  '/pay/callback': typeof PayCallbackRoute
  '/proposal/$slug': typeof ProposalSlugRoute
  '/thesis/$slug': typeof ThesisSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/online-calculation-tools/': typeof OnlineCalculationToolsIndexRoute
  '/proposal/': typeof ProposalIndexRoute
  '/thesis/': typeof ThesisIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/fields/$slug': typeof AdminFieldsSlugRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/tickets/$id': typeof DashboardTicketsIdRoute
  '/thesis/humanities/$slug': typeof ThesisHumanitiesSlugRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/article': typeof ArticleRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/downloads': typeof DownloadsRoute
  '/gams': typeof GamsRoute
  '/inquiry': typeof InquiryRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/project': typeof ProjectRoute
  '/refund': typeof RefundRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/simulation': typeof SimulationRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/fields': typeof AdminFieldsRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tezcoin': typeof AdminTezcoinRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/download/$slug': typeof DownloadSlugRoute
  '/online-calculation-tools/$slug': typeof OnlineCalculationToolsSlugRoute
  '/pay/callback': typeof PayCallbackRoute
  '/proposal/$slug': typeof ProposalSlugRoute
  '/thesis/$slug': typeof ThesisSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/online-calculation-tools': typeof OnlineCalculationToolsIndexRoute
  '/proposal': typeof ProposalIndexRoute
  '/thesis': typeof ThesisIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/fields/$slug': typeof AdminFieldsSlugRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/tickets/$id': typeof DashboardTicketsIdRoute
  '/thesis/humanities/$slug': typeof ThesisHumanitiesSlugRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/tickets': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/article': typeof ArticleRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/downloads': typeof DownloadsRoute
  '/gams': typeof GamsRoute
  '/inquiry': typeof InquiryRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/our-story': typeof OurStoryRoute
  '/privacy': typeof PrivacyRoute
  '/project': typeof ProjectRoute
  '/refund': typeof RefundRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/simulation': typeof SimulationRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/fields': typeof AdminFieldsRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tezcoin': typeof AdminTezcoinRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-study/$slug': typeof CaseStudySlugRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/download/$slug': typeof DownloadSlugRoute
  '/online-calculation-tools/$slug': typeof OnlineCalculationToolsSlugRoute
  '/pay/callback': typeof PayCallbackRoute
  '/proposal/$slug': typeof ProposalSlugRoute
  '/thesis/$slug': typeof ThesisSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/online-calculation-tools/': typeof OnlineCalculationToolsIndexRoute
  '/proposal/': typeof ProposalIndexRoute
  '/thesis/': typeof ThesisIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/fields/$slug': typeof AdminFieldsSlugRoute
  '/admin/tickets/$id': typeof AdminTicketsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/tickets/$id': typeof DashboardTicketsIdRoute
  '/thesis/humanities/$slug': typeof ThesisHumanitiesSlugRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$slug'
    | '/about'
    | '/achievements'
    | '/article'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/downloads'
    | '/gams'
    | '/inquiry'
    | '/join-us'
    | '/login'
    | '/our-story'
    | '/privacy'
    | '/project'
    | '/refund'
    | '/rules'
    | '/search'
    | '/simulation'
    | '/sitemap'
    | '/sitemap.xml'
    | '/statistics'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/fields'
    | '/admin/inquiries'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/tezcoin'
    | '/blog/$slug'
    | '/case-study/$slug'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/wallet'
    | '/download/$slug'
    | '/online-calculation-tools/$slug'
    | '/pay/callback'
    | '/proposal/$slug'
    | '/thesis/$slug'
    | '/tools/$slug'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/online-calculation-tools/'
    | '/proposal/'
    | '/thesis/'
    | '/tools/'
    | '/admin/fields/$slug'
    | '/admin/tickets/$id'
    | '/api/auth/$'
    | '/dashboard/projects/$id'
    | '/dashboard/tickets/$id'
    | '/thesis/humanities/$slug'
    | '/admin/tickets/'
    | '/dashboard/projects/'
    | '/dashboard/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/achievements'
    | '/article'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/downloads'
    | '/gams'
    | '/inquiry'
    | '/join-us'
    | '/login'
    | '/our-story'
    | '/privacy'
    | '/project'
    | '/refund'
    | '/rules'
    | '/search'
    | '/simulation'
    | '/sitemap'
    | '/sitemap.xml'
    | '/statistics'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/fields'
    | '/admin/inquiries'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/tezcoin'
    | '/blog/$slug'
    | '/case-study/$slug'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/wallet'
    | '/download/$slug'
    | '/online-calculation-tools/$slug'
    | '/pay/callback'
    | '/proposal/$slug'
    | '/thesis/$slug'
    | '/tools/$slug'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/online-calculation-tools'
    | '/proposal'
    | '/thesis'
    | '/tools'
    | '/admin/fields/$slug'
    | '/admin/tickets/$id'
    | '/api/auth/$'
    | '/dashboard/projects/$id'
    | '/dashboard/tickets/$id'
    | '/thesis/humanities/$slug'
    | '/admin/tickets'
    | '/dashboard/projects'
    | '/dashboard/tickets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/$slug'
    | '/about'
    | '/achievements'
    | '/article'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/downloads'
    | '/gams'
    | '/inquiry'
    | '/join-us'
    | '/login'
    | '/our-story'
    | '/privacy'
    | '/project'
    | '/refund'
    | '/rules'
    | '/search'
    | '/simulation'
    | '/sitemap'
    | '/sitemap.xml'
    | '/statistics'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/fields'
    | '/admin/inquiries'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/tezcoin'
    | '/blog/$slug'
    | '/case-study/$slug'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/wallet'
    | '/download/$slug'
    | '/online-calculation-tools/$slug'
    | '/pay/callback'
    | '/proposal/$slug'
    | '/thesis/$slug'
    | '/tools/$slug'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/online-calculation-tools/'
    | '/proposal/'
    | '/thesis/'
    | '/tools/'
    | '/admin/fields/$slug'
    | '/admin/tickets/$id'
    | '/api/auth/$'
    | '/dashboard/projects/$id'
    | '/dashboard/tickets/$id'
    | '/thesis/humanities/$slug'
    | '/admin/tickets/'
    | '/dashboard/projects/'
    | '/dashboard/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ArticleRoute: typeof ArticleRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DownloadsRoute: typeof DownloadsRoute
  GamsRoute: typeof GamsRoute
  InquiryRoute: typeof InquiryRoute
  JoinUsRoute: typeof JoinUsRoute
  LoginRoute: typeof LoginRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectRoute: typeof ProjectRoute
  RefundRoute: typeof RefundRoute
  RulesRoute: typeof RulesRoute
  SearchRoute: typeof SearchRoute
  SimulationRoute: typeof SimulationRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatisticsRoute: typeof StatisticsRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudySlugRoute: typeof CaseStudySlugRoute
  DownloadSlugRoute: typeof DownloadSlugRoute
  OnlineCalculationToolsSlugRoute: typeof OnlineCalculationToolsSlugRoute
  PayCallbackRoute: typeof PayCallbackRoute
  ProposalSlugRoute: typeof ProposalSlugRoute
  ThesisSlugRoute: typeof ThesisSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  OnlineCalculationToolsIndexRoute: typeof OnlineCalculationToolsIndexRoute
  ProposalIndexRoute: typeof ProposalIndexRoute
  ThesisIndexRoute: typeof ThesisIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ThesisHumanitiesSlugRoute: typeof ThesisHumanitiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gams': {
      id: '/gams'
      path: '/gams'
      fullPath: '/gams'
      preLoaderRoute: typeof GamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tezcoin': {
      id: '/admin/tezcoin'
      path: '/tezcoin'
      fullPath: '/admin/tezcoin'
      preLoaderRoute: typeof AdminTezcoinRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/$slug': {
      id: '/case-study/$slug'
      path: '/case-study/$slug'
      fullPath: '/case-study/$slug'
      preLoaderRoute: typeof CaseStudySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/download/$slug': {
      id: '/download/$slug'
      path: '/download/$slug'
      fullPath: '/download/$slug'
      preLoaderRoute: typeof DownloadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-calculation-tools/': {
      id: '/online-calculation-tools/'
      path: '/online-calculation-tools'
      fullPath: '/online-calculation-tools/'
      preLoaderRoute: typeof OnlineCalculationToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-calculation-tools/$slug': {
      id: '/online-calculation-tools/$slug'
      path: '/online-calculation-tools/$slug'
      fullPath: '/online-calculation-tools/$slug'
      preLoaderRoute: typeof OnlineCalculationToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/callback': {
      id: '/pay/callback'
      path: '/pay/callback'
      fullPath: '/pay/callback'
      preLoaderRoute: typeof PayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/': {
      id: '/proposal/'
      path: '/proposal'
      fullPath: '/proposal/'
      preLoaderRoute: typeof ProposalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$slug': {
      id: '/proposal/$slug'
      path: '/proposal/$slug'
      fullPath: '/proposal/$slug'
      preLoaderRoute: typeof ProposalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thesis/': {
      id: '/thesis/'
      path: '/thesis'
      fullPath: '/thesis/'
      preLoaderRoute: typeof ThesisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thesis/$slug': {
      id: '/thesis/$slug'
      path: '/thesis/$slug'
      fullPath: '/thesis/$slug'
      preLoaderRoute: typeof ThesisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fields/$slug': {
      id: '/admin/fields/$slug'
      path: '/$slug'
      fullPath: '/admin/fields/$slug'
      preLoaderRoute: typeof AdminFieldsSlugRouteImport
      parentRoute: typeof AdminFieldsRoute
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tickets/$id': {
      id: '/admin/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AdminTicketsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tickets/': {
      id: '/dashboard/tickets/'
      path: '/tickets'
      fullPath: '/dashboard/tickets/'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tickets/$id': {
      id: '/dashboard/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/dashboard/tickets/$id'
      preLoaderRoute: typeof DashboardTicketsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/thesis/humanities/$slug': {
      id: '/thesis/humanities/$slug'
      path: '/thesis/humanities/$slug'
      fullPath: '/thesis/humanities/$slug'
      preLoaderRoute: typeof ThesisHumanitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminFieldsRouteChildren {
  AdminFieldsSlugRoute: typeof AdminFieldsSlugRoute
}

const AdminFieldsRouteChildren: AdminFieldsRouteChildren = {
  AdminFieldsSlugRoute: AdminFieldsSlugRoute,
}

const AdminFieldsRouteWithChildren = AdminFieldsRoute._addFileChildren(
  AdminFieldsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminFieldsRoute: typeof AdminFieldsRouteWithChildren
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTezcoinRoute: typeof AdminTezcoinRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTicketsIdRoute: typeof AdminTicketsIdRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminFieldsRoute: AdminFieldsRouteWithChildren,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTezcoinRoute: AdminTezcoinRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTicketsIdRoute: AdminTicketsIdRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardTicketsIdRoute: typeof DashboardTicketsIdRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardTicketsIdRoute: DashboardTicketsIdRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ArticleRoute: ArticleRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DownloadsRoute: DownloadsRoute,
  GamsRoute: GamsRoute,
  InquiryRoute: InquiryRoute,
  JoinUsRoute: JoinUsRoute,
  LoginRoute: LoginRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectRoute: ProjectRoute,
  RefundRoute: RefundRoute,
  RulesRoute: RulesRoute,
  SearchRoute: SearchRoute,
  SimulationRoute: SimulationRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatisticsRoute: StatisticsRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudySlugRoute: CaseStudySlugRoute,
  DownloadSlugRoute: DownloadSlugRoute,
  OnlineCalculationToolsSlugRoute: OnlineCalculationToolsSlugRoute,
  PayCallbackRoute: PayCallbackRoute,
  ProposalSlugRoute: ProposalSlugRoute,
  ThesisSlugRoute: ThesisSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  OnlineCalculationToolsIndexRoute: OnlineCalculationToolsIndexRoute,
  ProposalIndexRoute: ProposalIndexRoute,
  ThesisIndexRoute: ThesisIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ThesisHumanitiesSlugRoute: ThesisHumanitiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
