<?php
/**
 * Original published PAGE content extracted from sep_posts + WPCode,
 * stored as Flexible Page Builder sections and `_teznevise_*` custom fields.
 *
 * Source JSON: inc/extracted-page-fields.json
 * Generated by: scripts/extract-shortcode-pages.py
 *
 * Contract:
 * - Pages only. Never reads or writes post_type=post.
 * - Never changes slug, title, parent, status, dates, or post_content.
 * - Empty redesign seed pages (about, service-thesis, …) are skipped;
 *   those keep builder-defaults.json.
 *
 * @package Teznevise
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Absolute path to the extracted pages document.
 *
 * @return string
 */
function teznevise_extracted_pages_path() {
	return TEZNEVISE_DIR . '/inc/extracted-page-fields.json';
}

/**
 * Load and cache extracted page fields.
 *
 * @return array{meta:array,pages:array}
 */
function teznevise_extracted_document() {
	static $doc = null;
	if ( null !== $doc ) {
		return $doc;
	}
	$doc  = array(
		'meta'  => array(),
		'pages' => array(),
	);
	$path = teznevise_extracted_pages_path();
	if ( ! is_readable( $path ) ) {
		return $doc;
	}
	$raw  = file_get_contents( $path );
	$data = is_string( $raw ) ? json_decode( $raw, true ) : null;
	if ( ! is_array( $data ) ) {
		return $doc;
	}
	$doc['meta']  = isset( $data['meta'] ) && is_array( $data['meta'] ) ? $data['meta'] : array();
	$doc['pages'] = isset( $data['pages'] ) && is_array( $data['pages'] ) ? $data['pages'] : array();
	return $doc;
}

/**
 * Permalink path for a page (parent slugs included). Preserves original slugs.
 *
 * @param int $post_id Page ID.
 * @return string
 */
function teznevise_page_path( $post_id ) {
	$post_id = (int) $post_id;
	$post    = $post_id ? get_post( $post_id ) : null;
	if ( ! $post || 'page' !== $post->post_type ) {
		return '';
	}
	$parts  = array( (string) $post->post_name );
	$parent = (int) $post->post_parent;
	$guard  = 0;
	while ( $parent > 0 && $guard < 8 ) {
		++$guard;
		$p = get_post( $parent );
		if ( ! $p || 'page' !== $p->post_type ) {
			break;
		}
		if ( $p->post_name ) {
			array_unshift( $parts, (string) $p->post_name );
		}
		$parent = (int) $p->post_parent;
	}
	return implode( '/', array_filter( $parts ) );
}

/**
 * Extracted entry for a page path or unique slug.
 *
 * @param string $key Path (`thesis/chapter-one`) or slug.
 * @return array<string,mixed>
 */
function teznevise_extracted_entry( $key ) {
	$key = trim( (string) $key, '/' );
	if ( '' === $key ) {
		return array();
	}
	$doc = teznevise_extracted_document();
	if ( isset( $doc['pages'][ $key ] ) && is_array( $doc['pages'][ $key ] ) ) {
		return $doc['pages'][ $key ];
	}
	$matches = array();
	foreach ( $doc['pages'] as $entry ) {
		if ( is_array( $entry ) && isset( $entry['slug'] ) && $entry['slug'] === $key ) {
			$matches[] = $entry;
		}
	}
	return 1 === count( $matches ) ? $matches[0] : array();
}

/**
 * Extracted entry for an existing page post. Pages only.
 *
 * @param int $post_id Post ID.
 * @return array<string,mixed>
 */
function teznevise_extracted_entry_for_post( $post_id ) {
	$post_id = (int) $post_id;
	$post    = $post_id ? get_post( $post_id ) : null;
	if ( ! $post || 'page' !== $post->post_type ) {
		return array();
	}
	$path  = teznevise_page_path( $post_id );
	$entry = $path ? teznevise_extracted_entry( $path ) : array();
	if ( $entry ) {
		return $entry;
	}
	return teznevise_extracted_entry( (string) $post->post_name );
}

/**
 * Whether leftover post_content is an interactive widget that must still render.
 *
 * @param string $content Raw post_content.
 * @return bool
 */
function teznevise_is_interactive_shortcode_content( $content ) {
	$plain = trim( wp_strip_all_tags( (string) $content ) );
	if ( '' === $plain ) {
		return false;
	}
	return (bool) preg_match(
		'/\[(?:tz_descriptive|tz_anova|tz_ttest|tz_spearman|tz_pearson|tz_cronbach|tz_cvr|tz_power|tz_sample_size|tz_kr20|tz_cohens_kappa|tz_mann_whitney|tz_wilcoxon|tz_kruskal_wallis|tz_regression|tz_chi_square|tz_goodness_of_fit|tz_icc|tz_price_calculator|tz_price_box|tz_price_cta|gravityform|teznevise_downloads|teznevise_download_category)\b/i',
		$plain
	);
}

/**
 * Whether the current page should still print post_content alongside builder fields.
 *
 * @param int $post_id Optional post ID.
 * @return bool
 */
function teznevise_page_should_print_content( $post_id = 0 ) {
	$post_id = $post_id ? (int) $post_id : (int) get_the_ID();
	$raw     = (string) get_post_field( 'post_content', $post_id );
	if ( '' === trim( $raw ) ) {
		return false;
	}
	if ( function_exists( 'teznevise_builder_has_sections' ) && teznevise_builder_has_sections() ) {
		if ( function_exists( 'teznevise_is_legacy_shortcode_content' ) && teznevise_is_legacy_shortcode_content( $raw ) ) {
			return teznevise_is_interactive_shortcode_content( $raw );
		}
		return false;
	}
	return true;
}

/**
 * Allowed `_teznevise_*` keys we may write from extracted JSON.
 *
 * @return string[]
 */
function teznevise_extracted_meta_keys() {
	$keys = array();
	if ( function_exists( 'teznevise_page_meta_schema' ) ) {
		$keys = array_merge( $keys, array_keys( teznevise_page_meta_schema() ) );
	}
	if ( function_exists( 'teznevise_page_meta_schema_extra' ) ) {
		$keys = array_merge( $keys, array_keys( teznevise_page_meta_schema_extra() ) );
	}
	return $keys;
}

/**
 * Write extracted custom fields onto an existing page. Never updates the post row.
 *
 * @param int  $post_id         Page ID.
 * @param bool $replace_builder Overwrite builder JSON when already present.
 * @param bool $dry_run         Do not write.
 * @return string created|updated|skipped|empty|invalid
 */
function teznevise_apply_extracted_fields( $post_id, $replace_builder = false, $dry_run = false ) {
	$post_id = (int) $post_id;
	$post    = $post_id ? get_post( $post_id ) : null;
	if ( ! $post || 'page' !== $post->post_type ) {
		return 'invalid';
	}

	$entry = teznevise_extracted_entry_for_post( $post_id );
	if ( ! $entry ) {
		return 'empty';
	}
	if ( isset( $entry['source'] ) && 'empty' === $entry['source'] ) {
		return 'empty';
	}

	$sections = isset( $entry['sections'] ) && is_array( $entry['sections'] ) ? $entry['sections'] : array();
	$meta     = isset( $entry['meta'] ) && is_array( $entry['meta'] ) ? $entry['meta'] : array();
	$template = isset( $entry['template'] ) ? (string) $entry['template'] : '';

	if ( ! $sections && ! $meta && ! $template ) {
		return 'empty';
	}

	$existing_builder = get_post_meta( $post_id, defined( 'TEZNEVISE_BUILDER_META' ) ? TEZNEVISE_BUILDER_META : '_teznevise_builder_sections', true );
	$had_builder      = is_string( $existing_builder ) && '' !== trim( $existing_builder ) && '[]' !== trim( $existing_builder );

	if ( $dry_run ) {
		if ( $sections && ( $replace_builder || ! $had_builder ) ) {
			return $had_builder ? 'updated' : 'created';
		}
		return $had_builder ? 'skipped' : 'created';
	}

	$wrote = false;

	if ( $sections && function_exists( 'teznevise_builder_save_sections' ) && ( $replace_builder || ! $had_builder ) ) {
		if ( teznevise_builder_save_sections( $post_id, $sections ) ) {
			$wrote = true;
		}
	}

	$allowed = teznevise_extracted_meta_keys();
	foreach ( $meta as $key => $value ) {
		if ( ! in_array( $key, $allowed, true ) ) {
			continue;
		}
		if ( ! is_string( $value ) || '' === $value ) {
			continue;
		}
		$meta_key = '_teznevise_' . $key;
		$current  = get_post_meta( $post_id, $meta_key, true );
		if ( '' !== (string) $current && ! $replace_builder ) {
			continue;
		}
		update_post_meta( $post_id, $meta_key, $value );
		$wrote = true;
	}

	if ( $template && 'page.php' !== $template ) {
		$current_tpl = (string) get_post_meta( $post_id, '_wp_page_template', true );
		if ( $replace_builder || '' === $current_tpl || 'default' === $current_tpl ) {
			update_post_meta( $post_id, '_wp_page_template', $template );
			$wrote = true;
		}
	}

	if ( ! $wrote ) {
		return 'skipped';
	}
	return $had_builder ? 'updated' : 'created';
}

/**
 * Apply extracted fields to every published page. Never touches posts.
 *
 * @param bool $replace_builder Overwrite existing builder JSON.
 * @param bool $dry_run         Dry run.
 * @return array{processed:int,created:int,updated:int,skipped:int,empty:int,errors:string[]}
 */
function teznevise_apply_extracted_to_pages( $replace_builder = false, $dry_run = false ) {
	$stats = array(
		'processed' => 0,
		'created'   => 0,
		'updated'   => 0,
		'skipped'   => 0,
		'empty'     => 0,
		'errors'    => array(),
	);

	$query = new WP_Query(
		array(
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
			'fields'         => 'ids',
		)
	);

	foreach ( $query->posts as $page_id ) {
		$stats['processed']++;
		$status = teznevise_apply_extracted_fields( (int) $page_id, $replace_builder, $dry_run );
		if ( isset( $stats[ $status ] ) ) {
			$stats[ $status ]++;
		} elseif ( 'invalid' === $status ) {
			$stats['errors'][] = sprintf( 'invalid page %d', (int) $page_id );
		} else {
			$stats['skipped']++;
		}
	}

	return $stats;
}
