<?php
/**
 * Original published PAGE content extracted from sep_posts + WPCode,
 * stored as Flexible Page Builder sections and `_teznevise_*` custom fields.
 *
 * Source JSON: inc/extracted-page-fields.json
 * Generated by: scripts/extract-shortcode-pages.py
 *
 * Contract:
 * - Pages only. Never reads or writes post_type=post.
 * - Never changes slug, title, parent, status, dates, or post_content.
 * - Empty redesign seed pages (about, service-thesis, …) are skipped;
 *   those keep builder-defaults.json.
 * - Automatic writes never replace administrator-owned builder JSON.
 *   Empty builder JSON may be filled without overwriting existing
 *   `_teznevise_*` fields or a non-default template. Field/template
 *   replacement is allowed only for default-seed data, unedited extracted
 *   payloads, generic v1.1 parser output, or an explicit force-replace.
 * - Manual provenance is honored even when builder JSON is empty ([]):
 *   administrator-owned _teznevise_* meta and non-default templates stay.
 *
 * @package Teznevise
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'TEZNEVISE_EXTRACTED_HASH_META', '_teznevise_extracted_hash' );
define( 'TEZNEVISE_BUILDER_PROVENANCE_META', '_teznevise_builder_provenance' );
define( 'TEZNEVISE_EXTRACTED_CURSOR_OPTION', 'teznevise_extracted_cursor' );

/**
 * Absolute path to the extracted pages document.
 *
 * @return string
 */
function teznevise_extracted_pages_path() {
	return TEZNEVISE_DIR . '/inc/extracted-page-fields.json';
}

/**
 * Load and cache extracted page fields.
 *
 * @return array{meta:array,pages:array}
 */
function teznevise_extracted_document() {
	static $doc = null;
	if ( null !== $doc ) {
		return $doc;
	}
	$doc  = array(
		'meta'  => array(),
		'pages' => array(),
	);
	$path = teznevise_extracted_pages_path();
	if ( ! is_readable( $path ) ) {
		return $doc;
	}
	$raw  = file_get_contents( $path );
	$data = is_string( $raw ) ? json_decode( $raw, true ) : null;
	if ( ! is_array( $data ) ) {
		return $doc;
	}
	$doc['meta']  = isset( $data['meta'] ) && is_array( $data['meta'] ) ? $data['meta'] : array();
	$doc['pages'] = isset( $data['pages'] ) && is_array( $data['pages'] ) ? $data['pages'] : array();
	return $doc;
}

/**
 * Permalink path for a page (parent slugs included). Preserves original slugs.
 *
 * @param int $post_id Page ID.
 * @return string
 */
function teznevise_page_path( $post_id ) {
	$post_id = (int) $post_id;
	$post    = $post_id ? get_post( $post_id ) : null;
	if ( ! $post || 'page' !== $post->post_type ) {
		return '';
	}
	$parts  = array( (string) $post->post_name );
	$parent = (int) $post->post_parent;
	$guard  = 0;
	while ( $parent > 0 && $guard < 8 ) {
		++$guard;
		$p = get_post( $parent );
		if ( ! $p || 'page' !== $p->post_type ) {
			break;
		}
		if ( $p->post_name ) {
			array_unshift( $parts, (string) $p->post_name );
		}
		$parent = (int) $p->post_parent;
	}
	return implode( '/', array_filter( $parts ) );
}

/**
 * Extracted entry for a page path or unique slug.
 *
 * @param string $key Path (`thesis/chapter-one`) or slug.
 * @return array<string,mixed>
 */
function teznevise_extracted_entry( $key ) {
	$key = trim( (string) $key, '/' );
	if ( '' === $key ) {
		return array();
	}
	$doc = teznevise_extracted_document();
	if ( isset( $doc['pages'][ $key ] ) && is_array( $doc['pages'][ $key ] ) ) {
		return $doc['pages'][ $key ];
	}
	$matches = array();
	foreach ( $doc['pages'] as $entry ) {
		if ( is_array( $entry ) && isset( $entry['slug'] ) && $entry['slug'] === $key ) {
			$matches[] = $entry;
		}
	}
	return 1 === count( $matches ) ? $matches[0] : array();
}

/**
 * Extracted entry for an existing page post. Pages only.
 *
 * @param int $post_id Post ID.
 * @return array<string,mixed>
 */
function teznevise_extracted_entry_for_post( $post_id ) {
	$post_id = (int) $post_id;
	$post    = $post_id ? get_post( $post_id ) : null;
	if ( ! $post || 'page' !== $post->post_type ) {
		return array();
	}
	$path  = teznevise_page_path( $post_id );
	$entry = $path ? teznevise_extracted_entry( $path ) : array();
	if ( $entry ) {
		return $entry;
	}
	return teznevise_extracted_entry( (string) $post->post_name );
}

/**
 * Interactive shortcodes that must keep rendering next to builder sections.
 *
 * @return string[]
 */
function teznevise_interactive_shortcode_names() {
	return array(
		'tz_descriptive',
		'tz_anova',
		'tz_ttest',
		'tz_spearman',
		'tz_pearson',
		'tz_cronbach',
		'tz_cvr',
		'tz_power',
		'tz_sample_size',
		'tz_kr20',
		'tz_cohens_kappa',
		'tz_mann_whitney',
		'tz_wilcoxon',
		'tz_kruskal_wallis',
		'tz_regression',
		'tz_chi_square',
		'tz_goodness_of_fit',
		'tz_icc',
		'tz_price_calculator',
		'tz_price_box',
		'tz_price_cta',
		'tz_service_cta',
		'tz_calculation_hub',
		'tz_careers_terms',
		'tz_join_form',
		'tz_join_widget',
		'gravityform',
		'gravityforms',
		'teznevise_downloads',
		'teznevise_download_category',
	);
}

/**
 * Regex fragment of interactive shortcode names.
 *
 * @return string
 */
function teznevise_interactive_shortcode_pattern() {
	$names = array_map( 'preg_quote', teznevise_interactive_shortcode_names() );
	return implode( '|', $names );
}

/**
 * Regex that matches an interactive shortcode in either self-closing or
 * enclosing form, including the inner body and the matching close tag.
 *
 * @return string Pattern without delimiters.
 */
function teznevise_interactive_shortcode_match_regex() {
	$pattern = teznevise_interactive_shortcode_pattern();
	return '\[(' . $pattern . ')\b[^\]]*\](?:(.*?)\s*\[\/\1\])?';
}

/**
 * Whether leftover post_content contains an interactive widget that must still render.
 * Detects the shortcode anywhere, including mixed HTML / multiple tags.
 *
 * @param string $content Raw post_content.
 * @return bool
 */
function teznevise_is_interactive_shortcode_content( $content ) {
	$plain = (string) $content;
	if ( function_exists( 'teznevise_normalize_shortcode_quotes' ) ) {
		$plain = teznevise_normalize_shortcode_quotes( $plain );
	}
	$plain = trim( wp_strip_all_tags( $plain ) );
	if ( '' === $plain ) {
		return false;
	}
	$pattern = teznevise_interactive_shortcode_pattern();
	return (bool) preg_match( '/\[(?:' . $pattern . ')\b/i', $plain );
}

/**
 * Return classic-editor prose after shortcodes are removed.
 *
 * Builder sections already represent the structured page. This keeps any
 * administrator-authored long-form copy available without duplicating forms,
 * calculators, or a legacy shortcode layout.
 *
 * @param string $content Raw post content.
 * @return string
 */
function teznevise_page_classic_copy( $content ) {
	$content = (string) $content;
	if ( function_exists( 'teznevise_normalize_shortcode_quotes' ) ) {
		$content = teznevise_normalize_shortcode_quotes( $content );
	}
	return trim( wp_strip_all_tags( strip_shortcodes( $content ) ) );
}

/**
 * Remove only the interactive shortcode tags that already render above the
 * disclosure, leaving administrator-authored classic prose untouched.
 *
 * @param string $content Raw post content.
 * @return string
 */
function teznevise_page_without_interactive_shortcodes( $content ) {
	$content = (string) $content;
	if ( function_exists( 'teznevise_normalize_shortcode_quotes' ) ) {
		$content = teznevise_normalize_shortcode_quotes( $content );
	}
	$pattern = teznevise_interactive_shortcode_match_regex();
	return (string) preg_replace( '/' . $pattern . '/is', '', $content );
}

/**
 * Render classic editor copy through normal WordPress formatting filters while
 * bypassing this disclosure filter for the nested rendering pass.
 *
 * @param string $content Raw classic content.
 * @return string
 */
function teznevise_render_classic_page_content( $content ) {
	global $teznevise_rendering_classic_page_content;
	$previous = ! empty( $teznevise_rendering_classic_page_content );
	$teznevise_rendering_classic_page_content = true;
	$rendered = apply_filters( 'the_content', $content );
	$teznevise_rendering_classic_page_content = $previous;
	return $rendered;
}

/**
 * Wrap classic-editor content in the shared accessible "show more" pattern.
 *
 * @param string $content Rendered page content.
 * @param int    $post_id Page ID.
 * @return string
 */
function teznevise_page_content_disclosure_markup( $content, $post_id = 0 ) {
	$post_id = $post_id ? (int) $post_id : (int) get_the_ID();
	if ( '' === teznevise_page_classic_copy( $content ) ) {
		return '';
	}
	$target_id = 'tz-classic-content-' . $post_id;
	ob_start();
	?>
	<div class="seo-panel seo-disclosure tz-classic-disclosure" data-reveal>
		<div class="seo-label"><?php esc_html_e( 'محتوای تکمیلی', 'teznevise' ); ?></div>
		<h2><?php esc_html_e( 'جزئیات و توضیحات بیشتر', 'teznevise' ); ?></h2>
		<div class="seo-more-content article-content longcopy" id="<?php echo esc_attr( $target_id ); ?>">
			<?php echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- rendered through the_content. ?>
		</div>
		<button aria-controls="<?php echo esc_attr( $target_id ); ?>" aria-expanded="false" class="seo-more-btn" data-seo-toggle type="button"><span aria-hidden="true" class="seo-more-mark">‹</span><span class="seo-more-text"><?php esc_html_e( 'مشاهده بیشتر', 'teznevise' ); ?></span></button>
	</div>
	<?php
	return (string) ob_get_clean();
}

/**
 * Apply the shared disclosure to normal classic-editor pages.
 *
 * Legacy shortcode layouts are retained untouched; builder templates use
 * teznevise_the_page_leftover_content() for their widget-plus-copy handling.
 *
 * @param string $content Rendered post content.
 * @return string
 */
function teznevise_filter_page_content_disclosure( $content ) {
	global $teznevise_rendering_classic_page_content;
	if ( ! empty( $teznevise_rendering_classic_page_content ) || is_admin() || ! is_singular( 'page' ) || ! in_the_loop() || ! is_main_query() ) {
		return $content;
	}
	$raw = (string) get_post_field( 'post_content', get_the_ID() );
	if ( function_exists( 'teznevise_is_legacy_shortcode_content' ) && teznevise_is_legacy_shortcode_content( $raw ) ) {
		return $content;
	}
	// Builder leftover is printed by teznevise_the_page_leftover_content().
	if ( function_exists( 'teznevise_builder_has_sections' ) && teznevise_builder_has_sections() ) {
		return $content;
	}
	if ( teznevise_is_interactive_shortcode_content( $raw ) ) {
		$interactive = teznevise_interactive_shortcodes_markup( $raw );
		$classic     = teznevise_render_classic_page_content( teznevise_page_without_interactive_shortcodes( $raw ) );
		$markup      = teznevise_page_content_disclosure_markup( $classic );
		$output      = '';
		if ( '' !== $interactive ) {
			$output .= '<div class="tz-interactive-page-content">' . do_shortcode( $interactive ) . '</div>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		}
		return $output . $markup;
	}
	// Classic-only pages keep their body visible. Do not hide it behind "مشاهده بیشتر".
	return $content;
}
add_filter( 'the_content', 'teznevise_filter_page_content_disclosure', 50 );

/**
 * Interactive shortcode tags extracted from mixed post_content.
 *
 * @param string $content Raw post_content.
 * @return string
 */
function teznevise_interactive_shortcodes_markup( $content ) {
	$content = (string) $content;
	if ( function_exists( 'teznevise_normalize_shortcode_quotes' ) ) {
		$content = teznevise_normalize_shortcode_quotes( $content );
	}
	$pattern = teznevise_interactive_shortcode_match_regex();
	if ( ! preg_match_all( '/' . $pattern . '/is', $content, $matches ) ) {
		return '';
	}
	$unique = array();
	foreach ( $matches[0] as $tag ) {
		$tag = trim( $tag );
		if ( '' !== $tag && ! in_array( $tag, $unique, true ) ) {
			$unique[] = $tag;
		}
	}
	return implode( "\n", $unique );
}

/**
 * Whether the current page should still print post_content alongside builder fields.
 *
 * @param int $post_id Optional post ID.
 * @return bool
 */
function teznevise_page_should_print_content( $post_id = 0 ) {
	$post_id = $post_id ? (int) $post_id : (int) get_the_ID();
	$raw     = (string) get_post_field( 'post_content', $post_id );
	if ( '' === trim( $raw ) ) {
		return false;
	}
	if ( function_exists( 'teznevise_builder_has_sections' ) && teznevise_builder_has_sections() ) {
		// Keep forms/calculators in place and expose remaining classic-editor copy
		// through the shared disclosure instead of silently dropping it.
		return teznevise_is_interactive_shortcode_content( $raw ) || '' !== teznevise_page_classic_copy( $raw );
	}
	return true;
}

/**
 * Print leftover page content. When builder sections exist, only execute
 * interactive shortcodes so migrated copy is not duplicated.
 *
 * @param int $post_id Optional post ID.
 */
function teznevise_the_page_leftover_content( $post_id = 0 ) {
	static $printed = false;
	if ( $printed ) {
		return;
	}
	$post_id = $post_id ? (int) $post_id : (int) get_the_ID();
	$raw     = (string) get_post_field( 'post_content', $post_id );
	$slug    = (string) get_post_field( 'post_name', $post_id );
	$has_builder = function_exists( 'teznevise_builder_has_sections' ) && teznevise_builder_has_sections();

	// Builder pages never call the_content(); run leftover calculators/forms here.
	if ( $has_builder && function_exists( 'teznevise_interactive_shortcodes_markup' ) ) {
		$markup = teznevise_interactive_shortcodes_markup( $raw );
		if ( '' !== $markup ) {
			echo '<div class="tz-interactive-page-content">' . do_shortcode( $markup ) . '</div>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		}
	}

	$classic_raw = function_exists( 'teznevise_page_without_interactive_shortcodes' )
		? teznevise_page_without_interactive_shortcodes( $raw )
		: $raw;
	if ( function_exists( 'strip_shortcodes' ) ) {
		$classic_raw = strip_shortcodes( $classic_raw );
	}
	$classic_raw = trim( (string) $classic_raw );
	$classic_txt = trim( wp_strip_all_tags( $classic_raw ) );
	if ( '' === $classic_txt && function_exists( 'teznevise_wxr_classic_for_slug' ) ) {
		$classic_raw = teznevise_wxr_classic_for_slug( $slug );
		$classic_txt = trim( wp_strip_all_tags( $classic_raw ) );
	}

	if ( '' === $classic_txt ) {
		$printed = true;
		return;
	}

	// Classic-only pages already print this as the main body.
	if ( ! $has_builder && $classic_raw === trim( $raw ) ) {
		$printed = true;
		return;
	}

	$html = function_exists( 'teznevise_render_classic_page_content' )
		? teznevise_render_classic_page_content( $classic_raw )
		: wp_kses_post( $classic_raw );
	$box  = teznevise_page_content_disclosure_markup( $html, $post_id );
	if ( '' !== $box ) {
		echo $box; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}
	$printed = true;
}

/**
 * Allowed `_teznevise_*` keys we may write from extracted JSON.
 *
 * @return string[]
 */
function teznevise_extracted_meta_keys() {
	$keys = array();
	if ( function_exists( 'teznevise_page_meta_schema' ) ) {
		$keys = array_merge( $keys, array_keys( teznevise_page_meta_schema() ) );
	}
	if ( function_exists( 'teznevise_page_meta_schema_extra' ) ) {
		$keys = array_merge( $keys, array_keys( teznevise_page_meta_schema_extra() ) );
	}
	return $keys;
}

/**
 * Stable hash of sanitized builder sections.
 *
 * @param array $sections Sections.
 * @return string
 */
function teznevise_sections_hash( $sections ) {
	if ( ! is_array( $sections ) ) {
		$sections = array();
	}
	if ( function_exists( 'teznevise_builder_sanitize_sections' ) ) {
		$sections = teznevise_builder_sanitize_sections( $sections );
	}
	$json = wp_json_encode( $sections, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );
	return is_string( $json ) ? hash( 'sha256', $json ) : '';
}

/**
 * Record who last wrote builder sections.
 *
 * @param int    $post_id Page ID.
 * @param string $kind    extracted|default-seed|manual.
 */
function teznevise_set_builder_provenance( $post_id, $kind ) {
	$post_id = (int) $post_id;
	$kind    = sanitize_key( $kind );
	if ( $post_id <= 0 || ! in_array( $kind, array( 'extracted', 'default-seed', 'manual' ), true ) ) {
		return;
	}
	update_post_meta( $post_id, TEZNEVISE_BUILDER_PROVENANCE_META, $kind );
}

/**
 * Whether a page is marked as administrator-owned.
 *
 * @param int $post_id Page ID.
 * @return bool
 */
function teznevise_page_has_manual_builder_provenance( $post_id ) {
	return 'manual' === (string) get_post_meta( (int) $post_id, TEZNEVISE_BUILDER_PROVENANCE_META, true );
}

/**
 * Stamp manual provenance after an administrator writes protected page fields.
 *
 * Used by metabox saves and REST meta updates. Extracted/seed writers call
 * teznevise_set_builder_provenance() with extracted|default-seed instead.
 *
 * @param int $post_id Page ID.
 */
function teznevise_stamp_manual_page_ownership( $post_id ) {
	$post_id = (int) $post_id;
	if ( $post_id <= 0 || 'page' !== get_post_type( $post_id ) ) {
		return;
	}
	teznevise_set_builder_provenance( $post_id, 'manual' );
}

/**
 * Builder-owned meta keys that must not trigger manual provenance.
 *
 * @return string[]
 */
function teznevise_builder_internal_meta_keys() {
	return array(
		'_teznevise_builder_sections',
		'_teznevise_builder_provenance',
		'_teznevise_extracted_hash',
	);
}

/**
 * Whether two stored page-meta values should be treated as unchanged.
 *
 * REST and metaboxes store booleans as '', '0', or '1', so a no-op false
 * rewrite must not look like a change.
 *
 * @param mixed $left  Prior value.
 * @param mixed $right Current value.
 * @return bool
 */
function teznevise_page_meta_values_equivalent( $left, $right ) {
	if ( $left === $right || (string) $left === (string) $right ) {
		return true;
	}
	$emptyish = static function ( $value ) {
		return false === $value || null === $value || '' === $value || 0 === $value || '0' === $value;
	};
	return $emptyish( $left ) && $emptyish( $right );
}

/**
 * Protected `_teznevise_*` keys present on a REST page request.
 *
 * Builder internals are excluded so extracted/seed/builder writers keep ownership.
 *
 * @param WP_REST_Request|mixed $request Request.
 * @return string[]
 */
function teznevise_protected_meta_keys_from_rest_request( $request ) {
	$meta = $request instanceof WP_REST_Request ? $request->get_param( 'meta' ) : null;
	if ( ! is_array( $meta ) ) {
		return array();
	}
	$skip = teznevise_builder_internal_meta_keys();
	$keys = array();
	foreach ( array_keys( $meta ) as $key ) {
		$key = (string) $key;
		if ( 0 !== strpos( $key, '_teznevise_' ) ) {
			continue;
		}
		if ( in_array( $key, $skip, true ) ) {
			continue;
		}
		$keys[] = $key;
	}
	return $keys;
}

/**
 * Prior protected meta values for the in-flight REST page update.
 *
 * rest_insert_page runs before REST writes meta; rest_after_insert_page
 * consumes the snapshot. Passing $set stores; omitting $set takes and clears.
 *
 * @param int        $post_id Page ID.
 * @param array|null $set     Snapshot to store.
 * @return array<string,mixed>
 */
function teznevise_rest_protected_meta_snapshot( $post_id, $set = null ) {
	static $store = array();
	$post_id      = (int) $post_id;
	if ( $post_id <= 0 ) {
		return array();
	}
	if ( null !== $set ) {
		$store[ $post_id ] = is_array( $set ) ? $set : array();
		return $store[ $post_id ];
	}
	$prior = isset( $store[ $post_id ] ) && is_array( $store[ $post_id ] ) ? $store[ $post_id ] : array();
	unset( $store[ $post_id ] );
	return $prior;
}

/**
 * Snapshot protected `_teznevise_*` values before REST writes page meta.
 *
 * @param WP_Post         $post     Inserted page.
 * @param WP_REST_Request $request  Request.
 * @param bool            $creating Creating vs updating.
 */
function teznevise_snapshot_rest_protected_meta( $post, $request, $_creating ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed
	if ( ! $post instanceof WP_Post || 'page' !== $post->post_type ) {
		return;
	}
	$keys = teznevise_protected_meta_keys_from_rest_request( $request );
	if ( empty( $keys ) ) {
		return;
	}
	$snap = array();
	foreach ( $keys as $key ) {
		$snap[ $key ] = get_post_meta( (int) $post->ID, $key, true );
	}
	teznevise_rest_protected_meta_snapshot( (int) $post->ID, $snap );
}
add_action( 'rest_insert_page', 'teznevise_snapshot_rest_protected_meta', 10, 3 );

/**
 * Stamp manual provenance when REST actually changed protected `_teznevise_*` fields.
 *
 * Compares stored values after the write against the rest_insert_page snapshot
 * so no-op payloads (clients resending existing meta) do not take ownership.
 *
 * @param WP_Post         $post     Inserted page.
 * @param WP_REST_Request $request  Request.
 * @param bool            $creating Creating vs updating.
 */
function teznevise_stamp_manual_from_rest( $post, $request, $_creating ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed
	if ( ! $post instanceof WP_Post || 'page' !== $post->post_type ) {
		return;
	}
	if ( ! current_user_can( 'edit_page', (int) $post->ID ) ) {
		return;
	}
	$prior = teznevise_rest_protected_meta_snapshot( (int) $post->ID );
	if ( empty( $prior ) ) {
		return;
	}
	foreach ( $prior as $key => $old ) {
		$now = get_post_meta( (int) $post->ID, (string) $key, true );
		if ( ! teznevise_page_meta_values_equivalent( $old, $now ) ) {
			teznevise_stamp_manual_page_ownership( (int) $post->ID );
			return;
		}
	}
}
add_action( 'rest_after_insert_page', 'teznevise_stamp_manual_from_rest', 10, 3 );

/**
 * Whether the page currently has a non-empty builder payload.
 *
 * `[]` and missing meta are empty.
 *
 * @param int $post_id Page ID.
 * @return bool
 */
function teznevise_extracted_page_has_builder_payload( $post_id ) {
	$meta_key = defined( 'TEZNEVISE_BUILDER_META' ) ? TEZNEVISE_BUILDER_META : '_teznevise_builder_sections';
	$existing = get_post_meta( (int) $post_id, $meta_key, true );
	return is_string( $existing ) && '' !== trim( $existing ) && '[]' !== trim( $existing );
}

/**
 * Whether existing builder/meta/template may be replaced by extracted data.
 *
 * Automatic runs never overwrite administrator-owned values. Empty builder
 * JSON is not treated as ownership of `_teznevise_*` fields or a
 * non-default `_wp_page_template`. Manual provenance is checked first.
 * Default-seed pages stay theme-owned even when builder JSON is empty, so
 * their fields/template can refresh. Extracted provenance keeps existing
 * custom fields; builder JSON can still refresh via
 * teznevise_extracted_builder_may_write() when the stored hash matches.
 *
 * @param int   $post_id Page ID.
 * @param array $entry   Extracted entry.
 * @param bool  $force   Administrator force-replace.
 * @return bool
 */
function teznevise_extracted_fields_are_replaceable( $post_id, $entry, $force = false ) {
	$post_id = (int) $post_id;
	if ( $force ) {
		return true;
	}

	// Manual ownership always wins — even when builder JSON is empty [].
	$provenance = (string) get_post_meta( $post_id, TEZNEVISE_BUILDER_PROVENANCE_META, true );
	if ( 'manual' === $provenance ) {
		return false;
	}

	// Default-seed remains theme-owned, including empty builder JSON.
	if ( 'default-seed' === $provenance ) {
		return true;
	}

	// Empty builder may be filled separately. It must not authorize
	// replacement of existing custom fields or a non-default template.
	if ( ! teznevise_extracted_page_has_builder_payload( $post_id ) ) {
		return false;
	}

	$stored_hash = (string) get_post_meta( $post_id, TEZNEVISE_EXTRACTED_HASH_META, true );
	$current     = function_exists( 'teznevise_builder_get_sections' ) ? teznevise_builder_get_sections( $post_id ) : array();
	$current_h   = teznevise_sections_hash( $current );

	// Previously extracted pages keep their existing custom fields unless
	// the administrator force-replaces.
	if ( 'extracted' === $provenance ) {
		return false;
	}


	$incoming = isset( $entry['sections'] ) && is_array( $entry['sections'] ) ? $entry['sections'] : array();
	if ( $incoming && $current_h === teznevise_sections_hash( $incoming ) ) {
		return true;
	}

	if ( function_exists( 'teznevise_builder_defaults_entry' ) && function_exists( 'teznevise_builder_conversion_key' ) ) {
		$key   = teznevise_builder_conversion_key( $post_id );
		$def   = $key ? teznevise_builder_defaults_entry( $key ) : array();
		$dsecs = ( ! empty( $def['builder'] ) && ! empty( $def['sections'] ) && is_array( $def['sections'] ) ) ? $def['sections'] : array();
		if ( $dsecs && $current_h === teznevise_sections_hash( $dsecs ) ) {
			return true;
		}
	}

	if ( function_exists( 'teznevise_migration_parse_content' ) ) {
		$post = get_post( $post_id );
		if ( $post && 'page' === $post->post_type ) {
			$parsed = teznevise_migration_parse_content( $post->post_content, $post->post_name );
			if ( $parsed && $current_h === teznevise_sections_hash( $parsed ) ) {
				return true;
			}
		}
	}

	return false;
}

/**
 * Whether extracted builder JSON may be written onto the page.
 *
 * Empty, non-manual builder payloads are fillable. Manual provenance is
 * never filled or replaced without $force. Unedited extracted builder JSON
 * may refresh from the dataset even when existing custom fields are kept.
 *
 * @param int   $post_id Page ID.
 * @param array $entry   Extracted entry.
 * @param bool  $force   Administrator force-replace.
 * @return bool
 */
function teznevise_extracted_builder_may_write( $post_id, $entry, $force = false ) {
	$post_id = (int) $post_id;
	if ( $force ) {
		return true;
	}
	$provenance = (string) get_post_meta( $post_id, TEZNEVISE_BUILDER_PROVENANCE_META, true );
	if ( 'manual' === $provenance ) {
		return false;
	}
	if ( ! teznevise_extracted_page_has_builder_payload( $post_id ) ) {
		return true;
	}
	if ( teznevise_extracted_fields_are_replaceable( $post_id, $entry, false ) ) {
		return true;
	}
	if ( 'extracted' === $provenance ) {
		$stored_hash = (string) get_post_meta( $post_id, TEZNEVISE_EXTRACTED_HASH_META, true );
		$current     = function_exists( 'teznevise_builder_get_sections' ) ? teznevise_builder_get_sections( $post_id ) : array();
		$current_h   = teznevise_sections_hash( $current );
		return ( '' === $stored_hash ) || ( $stored_hash === $current_h );
	}
	return false;
}

/**
 * Write extracted custom fields onto an existing page. Never updates the post row.
 *
 * @param int  $post_id         Page ID.
 * @param bool $replace_builder Administrator force-replace.
 * @param bool $dry_run         Do not write.
 * @return string created|updated|skipped|empty|invalid
 */
function teznevise_apply_extracted_fields( $post_id, $replace_builder = false, $dry_run = false ) {
	$post_id = (int) $post_id;
	$post    = $post_id ? get_post( $post_id ) : null;
	if ( ! $post || 'page' !== $post->post_type ) {
		return 'invalid';
	}

	$entry = teznevise_extracted_entry_for_post( $post_id );
	if ( ! $entry ) {
		return 'empty';
	}
	if ( isset( $entry['source'] ) && 'empty' === $entry['source'] ) {
		return 'empty';
	}

	$sections = isset( $entry['sections'] ) && is_array( $entry['sections'] ) ? $entry['sections'] : array();
	$meta     = isset( $entry['meta'] ) && is_array( $entry['meta'] ) ? $entry['meta'] : array();
	$template = isset( $entry['template'] ) ? (string) $entry['template'] : '';

	if ( ! $sections && ! $meta && ! $template ) {
		return 'empty';
	}

	$had_builder   = teznevise_extracted_page_has_builder_payload( $post_id );
	$overwrite     = teznevise_extracted_fields_are_replaceable( $post_id, $entry, (bool) $replace_builder );
	$write_builder = teznevise_extracted_builder_may_write( $post_id, $entry, (bool) $replace_builder );

	if ( $dry_run ) {
		if ( $sections && $write_builder ) {
			return $had_builder ? 'updated' : 'created';
		}
		$allowed = teznevise_extracted_meta_keys();
		foreach ( $meta as $key => $value ) {
			if ( ! in_array( $key, $allowed, true ) || ! is_string( $value ) || '' === $value ) {
				continue;
			}
			$current = get_post_meta( $post_id, '_teznevise_' . $key, true );
			if ( ( '' === (string) $current || $overwrite ) && (string) $current !== $value ) {
				return $had_builder ? 'updated' : 'created';
			}
		}
		if ( $template && 'page.php' !== $template ) {
			$current_tpl = (string) get_post_meta( $post_id, '_wp_page_template', true );
			if ( ( $overwrite || '' === $current_tpl || 'default' === $current_tpl ) && $current_tpl !== $template ) {
				return $had_builder ? 'updated' : 'created';
			}
		}
		return 'skipped';
	}

	$wrote = false;

	if ( $sections && function_exists( 'teznevise_builder_save_sections' ) && $write_builder ) {
		if ( teznevise_builder_save_sections( $post_id, $sections ) ) {
			$wrote = true;
		}
		teznevise_set_builder_provenance( $post_id, 'extracted' );
		update_post_meta( $post_id, TEZNEVISE_EXTRACTED_HASH_META, teznevise_sections_hash( $sections ) );
	}

	$allowed = teznevise_extracted_meta_keys();
	foreach ( $meta as $key => $value ) {
		if ( ! in_array( $key, $allowed, true ) ) {
			continue;
		}
		if ( ! is_string( $value ) || '' === $value ) {
			continue;
		}
		$meta_key = '_teznevise_' . $key;
		$current  = get_post_meta( $post_id, $meta_key, true );
		if ( '' !== (string) $current && ! $overwrite ) {
			continue;
		}
		if ( (string) $current === $value ) {
			continue;
		}
		if ( update_post_meta( $post_id, $meta_key, $value ) ) {
			$wrote = true;
		}
	}

	if ( $template && 'page.php' !== $template ) {
		$current_tpl = (string) get_post_meta( $post_id, '_wp_page_template', true );
		if ( $overwrite || '' === $current_tpl || 'default' === $current_tpl ) {
			if ( $current_tpl !== $template && update_post_meta( $post_id, '_wp_page_template', $template ) ) {
				$wrote = true;
			}
		}
	}

	if ( ! $wrote ) {
		return 'skipped';
	}
	return $had_builder ? 'updated' : 'created';
}

/**
 * Apply extracted fields to published pages. Never touches posts.
 *
 * @param bool $replace_builder Overwrite existing builder JSON when allowed.
 * @param bool $dry_run         Dry run.
 * @param int  $limit           Maximum pages to inspect (0 = all).
 * @param int  $offset          Query offset.
 * @return array{processed:int,created:int,updated:int,skipped:int,empty:int,errors:string[]}
 */
function teznevise_apply_extracted_to_pages( $replace_builder = false, $dry_run = false, $limit = 0, $offset = 0 ) {
	$stats = array(
		'processed' => 0,
		'created'   => 0,
		'updated'   => 0,
		'skipped'   => 0,
		'empty'     => 0,
		'errors'    => array(),
	);

	$query = new WP_Query(
		array(
			'post_type'              => 'page',
			'post_status'            => 'publish',
			'posts_per_page'         => $limit > 0 ? (int) $limit : -1,
			'offset'                 => max( 0, (int) $offset ),
			'orderby'                => 'ID',
			'order'                  => 'ASC',
			'no_found_rows'          => true,
			'fields'                 => 'ids',
			'update_post_meta_cache' => true,
			'update_post_term_cache' => false,
		)
	);

	foreach ( $query->posts as $page_id ) {
		$stats['processed']++;
		$status = teznevise_apply_extracted_fields( (int) $page_id, $replace_builder, $dry_run );
		if ( isset( $stats[ $status ] ) ) {
			$stats[ $status ]++;
		} elseif ( 'invalid' === $status ) {
			$stats['errors'][] = sprintf( 'invalid page %d', (int) $page_id );
		} else {
			$stats['skipped']++;
		}
	}

	return $stats;
}
